"""
Finance chart style helpers — implements style_chart.md v1.0 for matplotlib.

Import this before drawing anything:

    import finance_style as fs
    fs.apply()
    fig, ax = fs.new_chart(title="...", subtitle="...", source=fs.SOURCE)

Every colour below is a *role*, not a preference. Charts reference the role name;
the hex lives here and only here. See style_chart.md §2.1.
"""

from pathlib import Path

import matplotlib.pyplot as plt

# --------------------------------------------------------------------------
# Colour roles — style_chart.md §2.1
# --------------------------------------------------------------------------
SURFACE = "#FFFFFF"       # plot area and page
WASH = "#F7F7F7"          # panel fills, banding
GRID = "#E8E8E8"          # horizontal gridlines
CONTEXT_FILL = "#BDBDBD"  # de-emphasised bars and areas — never a thin line
CONTEXT_LINE = "#8C8C8C"  # de-emphasised lines and small marks
TEXT_2 = "#595959"        # subtitles, axis titles, axis labels
INK = "#262A33"           # titles, primary text, darkest series
ACCENT = "#0F5499"        # the single highlighted series
ALERT = "#990F3D"         # the one number that is a problem
GOOD = "#0D7680"          # favourable variance only
BAD = "#990F3D"           # unfavourable variance only

# Multi-series ramp, ordered by lightness — §2.2. Do not reshuffle.
SERIES = ["#262A33", "#0F5499", "#3D9199", "#93B2D1"]
SERIES_FILL_ONLY = {"#93B2D1"}  # series-4: 2.20:1 on white, fills only

# --------------------------------------------------------------------------
# Layout constants — §4
# --------------------------------------------------------------------------
FIGSIZE = (9.0, 4.5)      # the chart block, 9.0" x 4.5"
BAR_WIDTH = 0.72          # 40% gap width for a single series
LINE_HIGHLIGHT = 2.5      # pt
LINE_CONTEXT = 1.5        # pt

# Type scale — §3. Seven levels, no more.
SZ_TITLE, SZ_SUBTITLE = 20, 14
SZ_AXIS_TITLE = SZ_AXIS_LABEL = SZ_DATA_LABEL = SZ_ANNOTATION = 11
SZ_SOURCE = 9

SOURCE = (
    "Source: Churn_Modelling.csv (synthetic, generated by generate_data.py) "
    "· Data as of 15 Aug 2026"
)

_STYLE_FILE = Path(__file__).with_name("finance.mplstyle")


def apply():
    """Load finance.mplstyle. Call once before drawing."""
    plt.style.use(_STYLE_FILE)


# --------------------------------------------------------------------------
# Number formatting — vi-VN, §5
# --------------------------------------------------------------------------
def vn(x, dp=0):
    """Format a number vi-VN: dot thousands, comma decimal, U+2212 for minus."""
    s = f"{abs(x):,.{dp}f}".replace(",", "\x00").replace(".", ",").replace("\x00", ".")
    return ("−" if x < 0 else "") + s


def pct(x, dp=0):
    """Percentage for a chart: 0 dp by default (§5)."""
    return f"{vn(x, dp)}%"


def signed_pp(x, dp=0):
    """Signed percentage-point difference, e.g. '+19 pp' (§5)."""
    sign = "+" if x >= 0 else ""
    return f"{sign}{vn(x, dp)} pp"


# --------------------------------------------------------------------------
# Chart scaffolding
# --------------------------------------------------------------------------
def new_chart(title, subtitle, source=SOURCE, left=0.055, right=0.985,
              top=0.76, bottom=0.17, figsize=FIGSIZE):
    """
    Build a compliant chart frame: takeaway title, descriptive subtitle, source line.

    Title/subtitle/source are drawn in figure coordinates so they stay left-aligned
    to the same margin regardless of axis labels (§1 rule 7, §3).
    """
    fig = plt.figure(figsize=figsize)
    ax = fig.add_axes((left, bottom, right - left, top - bottom))

    fig.text(0.055, 0.955, title, size=SZ_TITLE, weight="semibold",
             color=INK, ha="left", va="top")
    fig.text(0.055, 0.855, subtitle, size=SZ_SUBTITLE,
             color=TEXT_2, ha="left", va="top")
    fig.text(0.055, 0.035, source, size=SZ_SOURCE,
             color=CONTEXT_LINE, ha="left", va="bottom")
    return fig, ax


def declutter(ax, value_axis="y", gridlines=False, baseline=True):
    """
    Strip chart junk (§1 rule 6, §4).

    value_axis  'y' for columns, 'x' for horizontal bars, None to keep both.
    gridlines   False by default — direct data labels make them redundant.
    baseline    keep the zero baseline on column charts; drop it on horizontal bars.
    """
    for side in ("top", "right", "left"):
        ax.spines[side].set_visible(False)
    ax.spines["bottom"].set_visible(baseline)
    if baseline:
        ax.spines["bottom"].set_color(TEXT_2)
        ax.spines["bottom"].set_linewidth(0.75)

    ax.tick_params(axis="both", length=0, colors=TEXT_2, labelsize=SZ_AXIS_LABEL)
    ax.set_axisbelow(True)

    ax.grid(False)
    if gridlines:
        ax.grid(axis="y", color=GRID, linewidth=0.75)  # horizontal only, §4

    # The value axis is removed when every mark carries a direct label (§1 rule 5).
    if value_axis == "y":
        ax.yaxis.set_visible(False)
    elif value_axis == "x":
        ax.xaxis.set_visible(False)
    return ax


def axis_title(ax, text, axis="x"):
    """Axis titles sit horizontally and left-aligned — never rotated (§3)."""
    if axis == "x":
        ax.set_xlabel(text, size=SZ_AXIS_TITLE, color=TEXT_2, loc="left")
    else:
        # matplotlib rejects loc= alongside ha=, so place it explicitly:
        # horizontal, sitting above the top of the axis (guide §3).
        ax.set_ylabel(text, size=SZ_AXIS_TITLE, color=TEXT_2,
                      rotation=0, ha="left", va="bottom")
        ax.yaxis.set_label_coords(0.0, 1.02)


def label_columns(ax, bars, values, colors, highlight_color, fmt=pct, pad=1.5):
    """Data labels outside the end of each column; semibold on the highlight (§3)."""
    for bar, value, color in zip(bars, values, colors):
        weight = "semibold" if color == highlight_color else "normal"
        label_color = color if color == highlight_color else TEXT_2
        ax.text(bar.get_x() + bar.get_width() / 2, value + pad, fmt(value),
                ha="center", va="bottom", size=SZ_DATA_LABEL,
                weight=weight, color=label_color)


def label_bars(ax, bars, values, colors, highlight_color, fmt=pct, pad=1.0):
    """Data labels outside the end of each horizontal bar."""
    for bar, value, color in zip(bars, values, colors):
        weight = "semibold" if color == highlight_color else "normal"
        label_color = color if color == highlight_color else TEXT_2
        ax.text(value + pad, bar.get_y() + bar.get_height() / 2, fmt(value),
                ha="left", va="center", size=SZ_DATA_LABEL,
                weight=weight, color=label_color)


def annotate(ax, text, xy, color=ACCENT, ha="left", va="bottom", xytext=None):
    """
    One or two annotations per chart (§3). A leader line is drawn in the same
    colour at 0.75 pt only when the text is placed away from its anchor.
    """
    if xytext is None:
        ax.text(xy[0], xy[1], text, color=color, size=SZ_ANNOTATION, ha=ha, va=va)
    else:
        ax.annotate(text, xy=xy, xytext=xytext, color=color, size=SZ_ANNOTATION,
                    ha=ha, va=va,
                    arrowprops=dict(arrowstyle="-", color=color, linewidth=0.75))


def direct_label(ax, text, xy, color, weight="semibold"):
    """Label a series at its own curve rather than in a legend (§1 rule 5)."""
    ax.text(xy[0], xy[1], text, color=color, size=SZ_DATA_LABEL,
            weight=weight, ha="left", va="bottom")
